### ISSUE TITLE
Support for Pixelmon ver 9.2.2

### ISSUE THREAD

**Issue by OgPaine** [shizotoaster/pixelcringe#1]
there is an error with pixelmon 9.2.3  thats because "p_130073_" is null it does not happen in 9.2.2.

**Comment by shizotoaster** [comment]
Could you please send the latest.log file?

**Comment by OgPaine** [comment]
it's no your mod that's the issue it's pixelmon thats the problem. https://pixelmonmod.com/tracker.php?p=2&t=21703. i was saying having support for 9.2.2 would be nice if not it's all good. the latest log file is long gone

**Comment by shizotoaster** [comment]
9.2.2 is potentially supported so it might work if you edit the mods.toml file. I'll double check that and upload a hotfix later
